### ISSUE TITLE
Show threshold results as passed/failed tests 

### ISSUE THREAD

**Issue by mbolotov** [k6io/intellij-plugin#3]
It's possible to parse output of the k6 script execution and show threshold results within IntelliJ test console:
![image](https://user-images.githubusercontent.com/19785715/111438292-20d7ab00-8715-11eb-8b52-1ae9fc5ae78d.png)

**Comment by ppcano** [comment]
k6 does not support a standard API to return threshold information. Therefore, at this moment, this features relies on parsing the k6 console output to show the threshold info on the IntelliJ UI.  

I do not suggest implementing it because k6 console output could change. 

On the other hand, k6 supports the [handleSummary callback](https://k6.io/docs/results-visualization/end-of-test-summary#handlesummary-callback) to return this type of information. I am not sure how it could look like this type of integration because it requires script changes.
